name: Submit RPC Endpoint
description: Submit Your RPC Endpoint
title: "[ADD-RPC] <title>"
body:
  - type: input
    id: rpc-http
    attributes:
      label: Http Endpoint
      description: Http rpc endpoint
      placeholder: ex. 100.100.100.100:9933
    validations:
      required: true
  - type: input
    id: rpc-ws
    attributes:
      label: Websocket Endpoint
      description: Websocket rpc endpoint
      placeholder: ex. 100.100.100.100:9944
    validations:
      required: true
  - type: input
    attributes:
      label: Address
      description: Your rewards address
    validations:
      required: true
