name: Submit RPC Endpoint
description: Submit Your RPC Endpoint
title: "[ADD-RPC] <title>"
body:
  - type: dropdown
    id: chain
    attributes:
      label: Chain
      description: Chain
      options:
        - Darwinia
        - Crab
    validations:
      required: true
  - type: input
    id: rpc-ws
    attributes:
      label: Websocket Endpoint
      description: Websocket rpc endpoint
      placeholder: ex. 100.100.100.100:9944
    validations:
      required: true
  - type: input
    attributes:
      label: Address
      description: Your rewards address
    validations:
      required: true
