name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-rpc:
    name: Deploy rpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate cds
        run: scripts/generate-cds.sh

      - name: Trigger deploy
        run: |
          gh workflow run \
            trigger.yml \
            --ref=main \
            --repo=darwinia-network/ansible-playbooks \
            --raw-field=file=roles/community-rpc/files/cds.yaml \
            --raw-field="content=$(cat dist/cds.local.yaml)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

