name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DOCKER_REGISTRY: ghcr.io

jobs:
  release-fishnet:
    name: Release fishnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build fishnet
        run: |
          cd analysis/fishnet
          cargo build --release

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Tag
        uses: olegtarasov/get-tag@v2.1
      - name: Sha
        uses: benjlevesque/short-sha@v1.2

      - name: Publish docker image hash
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: .maintain/docker/fishnet.Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/fishnet:sha-${{ env.SHA }}

      - name: Publish docker image tag
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: .
          file: .maintain/docker/dashboard.Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/fishnet:${{ env.GIT_TAG_NAME }}


  release-dashboard:
    name: Release dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build dashboard
        run: |
          cd analysis/dashboard
          yarn install
          yarn build:prod

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Tag
        uses: olegtarasov/get-tag@v2.1
      - name: Sha
        uses: benjlevesque/short-sha@v1.2

      - name: Publish docker image hash
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: .maintain/docker/dashboard.Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/dashboard:sha-${{ env.SHA }}

      - name: Publish docker image tag
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: .
          file: .maintain/docker/dashboard.Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/dashboard:${{ env.GIT_TAG_NAME }}
